// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.33.1
// source: auction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuctionCommitment stores a commitment (hash) of serialized auction data keyed by auction end timestamp.
type AuctionCommitment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndTimestamp  string                 `protobuf:"bytes,1,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionCommitment) Reset() {
	*x = AuctionCommitment{}
	mi := &file_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionCommitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionCommitment) ProtoMessage() {}

func (x *AuctionCommitment) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionCommitment.ProtoReflect.Descriptor instead.
func (*AuctionCommitment) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{0}
}

func (x *AuctionCommitment) GetEndTimestamp() string {
	if x != nil {
		return x.EndTimestamp
	}
	return ""
}

func (x *AuctionCommitment) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// AuctionType is a simple wrapper to store the auction mode as a string (independent|coupled).
type AuctionType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionType) Reset() {
	*x = AuctionType{}
	mi := &file_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionType) ProtoMessage() {}

func (x *AuctionType) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionType.ProtoReflect.Descriptor instead.
func (*AuctionType) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{1}
}

func (x *AuctionType) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_auction_proto protoreflect.FileDescriptor

const file_auction_proto_rawDesc = "" +
	"\n" +
	"\rauction.proto\x12\x02pb\"K\n" +
	"\x11AuctionCommitment\x12\"\n" +
	"\fendTimestamp\x18\x01 \x01(\tR\fendTimestamp\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"#\n" +
	"\vAuctionType\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB<Z:github.com/johannww/phd-impl/chaincodes/common/internal/pbb\x06proto3"

var (
	file_auction_proto_rawDescOnce sync.Once
	file_auction_proto_rawDescData []byte
)

func file_auction_proto_rawDescGZIP() []byte {
	file_auction_proto_rawDescOnce.Do(func() {
		file_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auction_proto_rawDesc), len(file_auction_proto_rawDesc)))
	})
	return file_auction_proto_rawDescData
}

var file_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auction_proto_goTypes = []any{
	(*AuctionCommitment)(nil), // 0: pb.AuctionCommitment
	(*AuctionType)(nil),       // 1: pb.AuctionType
}
var file_auction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auction_proto_init() }
func file_auction_proto_init() {
	if File_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auction_proto_rawDesc), len(file_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auction_proto_goTypes,
		DependencyIndexes: file_auction_proto_depIdxs,
		MessageInfos:      file_auction_proto_msgTypes,
	}.Build()
	File_auction_proto = out.File
	file_auction_proto_goTypes = nil
	file_auction_proto_depIdxs = nil
}
