// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v7.34.1
// source: auction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuctionCommitment stores a commitment (hash) of serialized auction data keyed by auction end timestamp.
type AuctionCommitment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndTimestamp  string                 `protobuf:"bytes,1,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionCommitment) Reset() {
	*x = AuctionCommitment{}
	mi := &file_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionCommitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionCommitment) ProtoMessage() {}

func (x *AuctionCommitment) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionCommitment.ProtoReflect.Descriptor instead.
func (*AuctionCommitment) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{0}
}

func (x *AuctionCommitment) GetEndTimestamp() string {
	if x != nil {
		return x.EndTimestamp
	}
	return ""
}

func (x *AuctionCommitment) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// AuctionType is a simple wrapper to store the auction mode as a string (independent|coupled).
type AuctionType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionType) Reset() {
	*x = AuctionType{}
	mi := &file_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionType) ProtoMessage() {}

func (x *AuctionType) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionType.ProtoReflect.Descriptor instead.
func (*AuctionType) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{1}
}

func (x *AuctionType) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// AuctionData represents the complete auction data including bids, policies, and companies.
type AuctionData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuctionID      uint64                 `protobuf:"varint,1,opt,name=auctionID,proto3" json:"auctionID,omitempty"`
	SellBids       []*SellBid             `protobuf:"bytes,2,rep,name=sellBids,proto3" json:"sellBids,omitempty"`
	BuyBids        []*BuyBid              `protobuf:"bytes,3,rep,name=buyBids,proto3" json:"buyBids,omitempty"`
	BidsMerkleRoot []byte                 `protobuf:"bytes,4,opt,name=bidsMerkleRoot,proto3" json:"bidsMerkleRoot,omitempty"`
	ActivePolicies []string               `protobuf:"bytes,5,rep,name=activePolicies,proto3" json:"activePolicies,omitempty"`
	CompaniesPvt   map[string]*Company    `protobuf:"bytes,6,rep,name=companiesPvt,proto3" json:"companiesPvt,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Coupled        bool                   `protobuf:"varint,7,opt,name=coupled,proto3" json:"coupled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuctionData) Reset() {
	*x = AuctionData{}
	mi := &file_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionData) ProtoMessage() {}

func (x *AuctionData) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionData.ProtoReflect.Descriptor instead.
func (*AuctionData) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{2}
}

func (x *AuctionData) GetAuctionID() uint64 {
	if x != nil {
		return x.AuctionID
	}
	return 0
}

func (x *AuctionData) GetSellBids() []*SellBid {
	if x != nil {
		return x.SellBids
	}
	return nil
}

func (x *AuctionData) GetBuyBids() []*BuyBid {
	if x != nil {
		return x.BuyBids
	}
	return nil
}

func (x *AuctionData) GetBidsMerkleRoot() []byte {
	if x != nil {
		return x.BidsMerkleRoot
	}
	return nil
}

func (x *AuctionData) GetActivePolicies() []string {
	if x != nil {
		return x.ActivePolicies
	}
	return nil
}

func (x *AuctionData) GetCompaniesPvt() map[string]*Company {
	if x != nil {
		return x.CompaniesPvt
	}
	return nil
}

func (x *AuctionData) GetCoupled() bool {
	if x != nil {
		return x.Coupled
	}
	return false
}

// SerializedAuctionData represents serialized auction data with its hash commitment.
type SerializedAuctionData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuctionDataBytes []byte                 `protobuf:"bytes,1,opt,name=auctionDataBytes,proto3" json:"auctionDataBytes,omitempty"`
	Sum              []byte                 `protobuf:"bytes,2,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SerializedAuctionData) Reset() {
	*x = SerializedAuctionData{}
	mi := &file_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerializedAuctionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedAuctionData) ProtoMessage() {}

func (x *SerializedAuctionData) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedAuctionData.ProtoReflect.Descriptor instead.
func (*SerializedAuctionData) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{3}
}

func (x *SerializedAuctionData) GetAuctionDataBytes() []byte {
	if x != nil {
		return x.AuctionDataBytes
	}
	return nil
}

func (x *SerializedAuctionData) GetSum() []byte {
	if x != nil {
		return x.Sum
	}
	return nil
}

// OffChainIndepAuctionResult represents the result of an independent off-chain auction
// with matched bids and adjusted bids (public and private components if applicable).
type OffChainIndepAuctionResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuctionID        uint64                 `protobuf:"varint,1,opt,name=auctionID,proto3" json:"auctionID,omitempty"`
	MatchedBids      []*MatchedBid          `protobuf:"bytes,2,rep,name=matchedBids,proto3" json:"matchedBids,omitempty"`
	AdjustedSellBids []*SellBid             `protobuf:"bytes,3,rep,name=adjustedSellBids,proto3" json:"adjustedSellBids,omitempty"`
	AdjustedBuyBids  []*BuyBid              `protobuf:"bytes,4,rep,name=adjustedBuyBids,proto3" json:"adjustedBuyBids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OffChainIndepAuctionResult) Reset() {
	*x = OffChainIndepAuctionResult{}
	mi := &file_auction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffChainIndepAuctionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffChainIndepAuctionResult) ProtoMessage() {}

func (x *OffChainIndepAuctionResult) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffChainIndepAuctionResult.ProtoReflect.Descriptor instead.
func (*OffChainIndepAuctionResult) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{4}
}

func (x *OffChainIndepAuctionResult) GetAuctionID() uint64 {
	if x != nil {
		return x.AuctionID
	}
	return 0
}

func (x *OffChainIndepAuctionResult) GetMatchedBids() []*MatchedBid {
	if x != nil {
		return x.MatchedBids
	}
	return nil
}

func (x *OffChainIndepAuctionResult) GetAdjustedSellBids() []*SellBid {
	if x != nil {
		return x.AdjustedSellBids
	}
	return nil
}

func (x *OffChainIndepAuctionResult) GetAdjustedBuyBids() []*BuyBid {
	if x != nil {
		return x.AdjustedBuyBids
	}
	return nil
}

// OffChainCoupledAuctionResult represents the result of a coupled off-chain auction
// with separate matched bids and adjusted bids for public and private components.
type OffChainCoupledAuctionResult struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MatchedBidsPublic       []*MatchedBid          `protobuf:"bytes,1,rep,name=matchedBidsPublic,proto3" json:"matchedBidsPublic,omitempty"`
	MatchedBidsPrivate      []*MatchedBid          `protobuf:"bytes,2,rep,name=matchedBidsPrivate,proto3" json:"matchedBidsPrivate,omitempty"`
	AdjustedSellBidsPublic  []*SellBid             `protobuf:"bytes,3,rep,name=adjustedSellBidsPublic,proto3" json:"adjustedSellBidsPublic,omitempty"`
	AdjustedSellBidsPrivate []*SellBid             `protobuf:"bytes,4,rep,name=adjustedSellBidsPrivate,proto3" json:"adjustedSellBidsPrivate,omitempty"`
	AdjustedBuyBidsPublic   []*BuyBid              `protobuf:"bytes,5,rep,name=adjustedBuyBidsPublic,proto3" json:"adjustedBuyBidsPublic,omitempty"`
	AdjustedBuyBidsPrivate  []*BuyBid              `protobuf:"bytes,6,rep,name=adjustedBuyBidsPrivate,proto3" json:"adjustedBuyBidsPrivate,omitempty"`
	AuctionID               uint64                 `protobuf:"varint,7,opt,name=auctionID,proto3" json:"auctionID,omitempty"` // to avoid marshalling conflicts with OffChainIndepAuctionResult
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OffChainCoupledAuctionResult) Reset() {
	*x = OffChainCoupledAuctionResult{}
	mi := &file_auction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffChainCoupledAuctionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffChainCoupledAuctionResult) ProtoMessage() {}

func (x *OffChainCoupledAuctionResult) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffChainCoupledAuctionResult.ProtoReflect.Descriptor instead.
func (*OffChainCoupledAuctionResult) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{5}
}

func (x *OffChainCoupledAuctionResult) GetMatchedBidsPublic() []*MatchedBid {
	if x != nil {
		return x.MatchedBidsPublic
	}
	return nil
}

func (x *OffChainCoupledAuctionResult) GetMatchedBidsPrivate() []*MatchedBid {
	if x != nil {
		return x.MatchedBidsPrivate
	}
	return nil
}

func (x *OffChainCoupledAuctionResult) GetAdjustedSellBidsPublic() []*SellBid {
	if x != nil {
		return x.AdjustedSellBidsPublic
	}
	return nil
}

func (x *OffChainCoupledAuctionResult) GetAdjustedSellBidsPrivate() []*SellBid {
	if x != nil {
		return x.AdjustedSellBidsPrivate
	}
	return nil
}

func (x *OffChainCoupledAuctionResult) GetAdjustedBuyBidsPublic() []*BuyBid {
	if x != nil {
		return x.AdjustedBuyBidsPublic
	}
	return nil
}

func (x *OffChainCoupledAuctionResult) GetAdjustedBuyBidsPrivate() []*BuyBid {
	if x != nil {
		return x.AdjustedBuyBidsPrivate
	}
	return nil
}

func (x *OffChainCoupledAuctionResult) GetAuctionID() uint64 {
	if x != nil {
		return x.AuctionID
	}
	return 0
}

var File_auction_proto protoreflect.FileDescriptor

const file_auction_proto_rawDesc = "" +
	"\n" +
	"\rauction.proto\x12\x02pb\x1a\x10properties.proto\x1a\n" +
	"bids.proto\"K\n" +
	"\x11AuctionCommitment\x12\"\n" +
	"\fendTimestamp\x18\x01 \x01(\tR\fendTimestamp\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"#\n" +
	"\vAuctionType\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xf9\x02\n" +
	"\vAuctionData\x12\x1c\n" +
	"\tauctionID\x18\x01 \x01(\x04R\tauctionID\x12'\n" +
	"\bsellBids\x18\x02 \x03(\v2\v.pb.SellBidR\bsellBids\x12$\n" +
	"\abuyBids\x18\x03 \x03(\v2\n" +
	".pb.BuyBidR\abuyBids\x12&\n" +
	"\x0ebidsMerkleRoot\x18\x04 \x01(\fR\x0ebidsMerkleRoot\x12&\n" +
	"\x0eactivePolicies\x18\x05 \x03(\tR\x0eactivePolicies\x12E\n" +
	"\fcompaniesPvt\x18\x06 \x03(\v2!.pb.AuctionData.CompaniesPvtEntryR\fcompaniesPvt\x12\x18\n" +
	"\acoupled\x18\a \x01(\bR\acoupled\x1aL\n" +
	"\x11CompaniesPvtEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.pb.CompanyR\x05value:\x028\x01\"U\n" +
	"\x15SerializedAuctionData\x12*\n" +
	"\x10auctionDataBytes\x18\x01 \x01(\fR\x10auctionDataBytes\x12\x10\n" +
	"\x03sum\x18\x02 \x01(\fR\x03sum\"\xdb\x01\n" +
	"\x1aOffChainIndepAuctionResult\x12\x1c\n" +
	"\tauctionID\x18\x01 \x01(\x04R\tauctionID\x120\n" +
	"\vmatchedBids\x18\x02 \x03(\v2\x0e.pb.MatchedBidR\vmatchedBids\x127\n" +
	"\x10adjustedSellBids\x18\x03 \x03(\v2\v.pb.SellBidR\x10adjustedSellBids\x124\n" +
	"\x0fadjustedBuyBids\x18\x04 \x03(\v2\n" +
	".pb.BuyBidR\x0fadjustedBuyBids\"\xcc\x03\n" +
	"\x1cOffChainCoupledAuctionResult\x12<\n" +
	"\x11matchedBidsPublic\x18\x01 \x03(\v2\x0e.pb.MatchedBidR\x11matchedBidsPublic\x12>\n" +
	"\x12matchedBidsPrivate\x18\x02 \x03(\v2\x0e.pb.MatchedBidR\x12matchedBidsPrivate\x12C\n" +
	"\x16adjustedSellBidsPublic\x18\x03 \x03(\v2\v.pb.SellBidR\x16adjustedSellBidsPublic\x12E\n" +
	"\x17adjustedSellBidsPrivate\x18\x04 \x03(\v2\v.pb.SellBidR\x17adjustedSellBidsPrivate\x12@\n" +
	"\x15adjustedBuyBidsPublic\x18\x05 \x03(\v2\n" +
	".pb.BuyBidR\x15adjustedBuyBidsPublic\x12B\n" +
	"\x16adjustedBuyBidsPrivate\x18\x06 \x03(\v2\n" +
	".pb.BuyBidR\x16adjustedBuyBidsPrivate\x12\x1c\n" +
	"\tauctionID\x18\a \x01(\x04R\tauctionIDB<Z:github.com/johannww/phd-impl/chaincodes/common/internal/pbb\x06proto3"

var (
	file_auction_proto_rawDescOnce sync.Once
	file_auction_proto_rawDescData []byte
)

func file_auction_proto_rawDescGZIP() []byte {
	file_auction_proto_rawDescOnce.Do(func() {
		file_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auction_proto_rawDesc), len(file_auction_proto_rawDesc)))
	})
	return file_auction_proto_rawDescData
}

var file_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auction_proto_goTypes = []any{
	(*AuctionCommitment)(nil),            // 0: pb.AuctionCommitment
	(*AuctionType)(nil),                  // 1: pb.AuctionType
	(*AuctionData)(nil),                  // 2: pb.AuctionData
	(*SerializedAuctionData)(nil),        // 3: pb.SerializedAuctionData
	(*OffChainIndepAuctionResult)(nil),   // 4: pb.OffChainIndepAuctionResult
	(*OffChainCoupledAuctionResult)(nil), // 5: pb.OffChainCoupledAuctionResult
	nil,                                  // 6: pb.AuctionData.CompaniesPvtEntry
	(*SellBid)(nil),                      // 7: pb.SellBid
	(*BuyBid)(nil),                       // 8: pb.BuyBid
	(*MatchedBid)(nil),                   // 9: pb.MatchedBid
	(*Company)(nil),                      // 10: pb.Company
}
var file_auction_proto_depIdxs = []int32{
	7,  // 0: pb.AuctionData.sellBids:type_name -> pb.SellBid
	8,  // 1: pb.AuctionData.buyBids:type_name -> pb.BuyBid
	6,  // 2: pb.AuctionData.companiesPvt:type_name -> pb.AuctionData.CompaniesPvtEntry
	9,  // 3: pb.OffChainIndepAuctionResult.matchedBids:type_name -> pb.MatchedBid
	7,  // 4: pb.OffChainIndepAuctionResult.adjustedSellBids:type_name -> pb.SellBid
	8,  // 5: pb.OffChainIndepAuctionResult.adjustedBuyBids:type_name -> pb.BuyBid
	9,  // 6: pb.OffChainCoupledAuctionResult.matchedBidsPublic:type_name -> pb.MatchedBid
	9,  // 7: pb.OffChainCoupledAuctionResult.matchedBidsPrivate:type_name -> pb.MatchedBid
	7,  // 8: pb.OffChainCoupledAuctionResult.adjustedSellBidsPublic:type_name -> pb.SellBid
	7,  // 9: pb.OffChainCoupledAuctionResult.adjustedSellBidsPrivate:type_name -> pb.SellBid
	8,  // 10: pb.OffChainCoupledAuctionResult.adjustedBuyBidsPublic:type_name -> pb.BuyBid
	8,  // 11: pb.OffChainCoupledAuctionResult.adjustedBuyBidsPrivate:type_name -> pb.BuyBid
	10, // 12: pb.AuctionData.CompaniesPvtEntry.value:type_name -> pb.Company
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_auction_proto_init() }
func file_auction_proto_init() {
	if File_auction_proto != nil {
		return
	}
	file_properties_proto_init()
	file_bids_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auction_proto_rawDesc), len(file_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auction_proto_goTypes,
		DependencyIndexes: file_auction_proto_depIdxs,
		MessageInfos:      file_auction_proto_msgTypes,
	}.Build()
	File_auction_proto = out.File
	file_auction_proto_goTypes = nil
	file_auction_proto_depIdxs = nil
}
