// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.33.1
// source: bids.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrivatePrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         int64                  `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	BidID         []string               `protobuf:"bytes,2,rep,name=bidID,proto3" json:"bidID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivatePrice) Reset() {
	*x = PrivatePrice{}
	mi := &file_bids_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivatePrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivatePrice) ProtoMessage() {}

func (x *PrivatePrice) ProtoReflect() protoreflect.Message {
	mi := &file_bids_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivatePrice.ProtoReflect.Descriptor instead.
func (*PrivatePrice) Descriptor() ([]byte, []int) {
	return file_bids_proto_rawDescGZIP(), []int{0}
}

func (x *PrivatePrice) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PrivatePrice) GetBidID() []string {
	if x != nil {
		return x.BidID
	}
	return nil
}

type PrivateQuantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AskQuantity   int64                  `protobuf:"varint,1,opt,name=askQuantity,proto3" json:"askQuantity,omitempty"`
	BidID         []string               `protobuf:"bytes,2,rep,name=bidID,proto3" json:"bidID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateQuantity) Reset() {
	*x = PrivateQuantity{}
	mi := &file_bids_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateQuantity) ProtoMessage() {}

func (x *PrivateQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_bids_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateQuantity.ProtoReflect.Descriptor instead.
func (*PrivateQuantity) Descriptor() ([]byte, []int) {
	return file_bids_proto_rawDescGZIP(), []int{1}
}

func (x *PrivateQuantity) GetAskQuantity() int64 {
	if x != nil {
		return x.AskQuantity
	}
	return 0
}

func (x *PrivateQuantity) GetBidID() []string {
	if x != nil {
		return x.BidID
	}
	return nil
}

type PrivateMultiplier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchingID    []string               `protobuf:"bytes,1,rep,name=matchingID,proto3" json:"matchingID,omitempty"`
	Scale         int64                  `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	Value         int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateMultiplier) Reset() {
	*x = PrivateMultiplier{}
	mi := &file_bids_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateMultiplier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateMultiplier) ProtoMessage() {}

func (x *PrivateMultiplier) ProtoReflect() protoreflect.Message {
	mi := &file_bids_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateMultiplier.ProtoReflect.Descriptor instead.
func (*PrivateMultiplier) Descriptor() ([]byte, []int) {
	return file_bids_proto_rawDescGZIP(), []int{2}
}

func (x *PrivateMultiplier) GetMatchingID() []string {
	if x != nil {
		return x.MatchingID
	}
	return nil
}

func (x *PrivateMultiplier) GetScale() int64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *PrivateMultiplier) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type BuyBid struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BuyerID         string                 `protobuf:"bytes,1,opt,name=buyerID,proto3" json:"buyerID,omitempty"`
	Timestamp       string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AskQuantity     int64                  `protobuf:"varint,3,opt,name=askQuantity,proto3" json:"askQuantity,omitempty"`
	PrivateQuantity *PrivateQuantity       `protobuf:"bytes,4,opt,name=privateQuantity,proto3" json:"privateQuantity,omitempty"`
	PrivatePrice    *PrivatePrice          `protobuf:"bytes,5,opt,name=privatePrice,proto3" json:"privatePrice,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BuyBid) Reset() {
	*x = BuyBid{}
	mi := &file_bids_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyBid) ProtoMessage() {}

func (x *BuyBid) ProtoReflect() protoreflect.Message {
	mi := &file_bids_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyBid.ProtoReflect.Descriptor instead.
func (*BuyBid) Descriptor() ([]byte, []int) {
	return file_bids_proto_rawDescGZIP(), []int{3}
}

func (x *BuyBid) GetBuyerID() string {
	if x != nil {
		return x.BuyerID
	}
	return ""
}

func (x *BuyBid) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *BuyBid) GetAskQuantity() int64 {
	if x != nil {
		return x.AskQuantity
	}
	return 0
}

func (x *BuyBid) GetPrivateQuantity() *PrivateQuantity {
	if x != nil {
		return x.PrivateQuantity
	}
	return nil
}

func (x *BuyBid) GetPrivatePrice() *PrivatePrice {
	if x != nil {
		return x.PrivatePrice
	}
	return nil
}

type SellBid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerID      string                 `protobuf:"bytes,1,opt,name=sellerID,proto3" json:"sellerID,omitempty"`
	CreditID      []string               `protobuf:"bytes,2,rep,name=creditID,proto3" json:"creditID,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Credit        *MintCredit            `protobuf:"bytes,4,opt,name=credit,proto3" json:"credit,omitempty"`
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PrivatePrice  *PrivatePrice          `protobuf:"bytes,6,opt,name=privatePrice,proto3" json:"privatePrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellBid) Reset() {
	*x = SellBid{}
	mi := &file_bids_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellBid) ProtoMessage() {}

func (x *SellBid) ProtoReflect() protoreflect.Message {
	mi := &file_bids_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellBid.ProtoReflect.Descriptor instead.
func (*SellBid) Descriptor() ([]byte, []int) {
	return file_bids_proto_rawDescGZIP(), []int{4}
}

func (x *SellBid) GetSellerID() string {
	if x != nil {
		return x.SellerID
	}
	return ""
}

func (x *SellBid) GetCreditID() []string {
	if x != nil {
		return x.CreditID
	}
	return nil
}

func (x *SellBid) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SellBid) GetCredit() *MintCredit {
	if x != nil {
		return x.Credit
	}
	return nil
}

func (x *SellBid) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SellBid) GetPrivatePrice() *PrivatePrice {
	if x != nil {
		return x.PrivatePrice
	}
	return nil
}

type MatchedBid struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BuyBid            *BuyBid                `protobuf:"bytes,1,opt,name=buyBid,proto3" json:"buyBid,omitempty"`
	SellBid           *SellBid               `protobuf:"bytes,2,opt,name=sellBid,proto3" json:"sellBid,omitempty"`
	Quantity          int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PrivatePrice      *PrivatePrice          `protobuf:"bytes,4,opt,name=privatePrice,proto3" json:"privatePrice,omitempty"`
	PrivateMultiplier *PrivateMultiplier     `protobuf:"bytes,5,opt,name=privateMultiplier,proto3" json:"privateMultiplier,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MatchedBid) Reset() {
	*x = MatchedBid{}
	mi := &file_bids_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchedBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchedBid) ProtoMessage() {}

func (x *MatchedBid) ProtoReflect() protoreflect.Message {
	mi := &file_bids_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchedBid.ProtoReflect.Descriptor instead.
func (*MatchedBid) Descriptor() ([]byte, []int) {
	return file_bids_proto_rawDescGZIP(), []int{5}
}

func (x *MatchedBid) GetBuyBid() *BuyBid {
	if x != nil {
		return x.BuyBid
	}
	return nil
}

func (x *MatchedBid) GetSellBid() *SellBid {
	if x != nil {
		return x.SellBid
	}
	return nil
}

func (x *MatchedBid) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *MatchedBid) GetPrivatePrice() *PrivatePrice {
	if x != nil {
		return x.PrivatePrice
	}
	return nil
}

func (x *MatchedBid) GetPrivateMultiplier() *PrivateMultiplier {
	if x != nil {
		return x.PrivateMultiplier
	}
	return nil
}

var File_bids_proto protoreflect.FileDescriptor

const file_bids_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"bids.proto\x12\x02pb\x1a\rcredits.proto\":\n" +
	"\fPrivatePrice\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x03R\x05price\x12\x14\n" +
	"\x05bidID\x18\x02 \x03(\tR\x05bidID\"I\n" +
	"\x0fPrivateQuantity\x12 \n" +
	"\vaskQuantity\x18\x01 \x01(\x03R\vaskQuantity\x12\x14\n" +
	"\x05bidID\x18\x02 \x03(\tR\x05bidID\"_\n" +
	"\x11PrivateMultiplier\x12\x1e\n" +
	"\n" +
	"matchingID\x18\x01 \x03(\tR\n" +
	"matchingID\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\x03R\x05scale\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\"\xd7\x01\n" +
	"\x06BuyBid\x12\x18\n" +
	"\abuyerID\x18\x01 \x01(\tR\abuyerID\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12 \n" +
	"\vaskQuantity\x18\x03 \x01(\x03R\vaskQuantity\x12=\n" +
	"\x0fprivateQuantity\x18\x04 \x01(\v2\x13.pb.PrivateQuantityR\x0fprivateQuantity\x124\n" +
	"\fprivatePrice\x18\x05 \x01(\v2\x10.pb.PrivatePriceR\fprivatePrice\"\xd9\x01\n" +
	"\aSellBid\x12\x1a\n" +
	"\bsellerID\x18\x01 \x01(\tR\bsellerID\x12\x1a\n" +
	"\bcreditID\x18\x02 \x03(\tR\bcreditID\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12&\n" +
	"\x06credit\x18\x04 \x01(\v2\x0e.pb.MintCreditR\x06credit\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x124\n" +
	"\fprivatePrice\x18\x06 \x01(\v2\x10.pb.PrivatePriceR\fprivatePrice\"\xee\x01\n" +
	"\n" +
	"MatchedBid\x12\"\n" +
	"\x06buyBid\x18\x01 \x01(\v2\n" +
	".pb.BuyBidR\x06buyBid\x12%\n" +
	"\asellBid\x18\x02 \x01(\v2\v.pb.SellBidR\asellBid\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x124\n" +
	"\fprivatePrice\x18\x04 \x01(\v2\x10.pb.PrivatePriceR\fprivatePrice\x12C\n" +
	"\x11privateMultiplier\x18\x05 \x01(\v2\x15.pb.PrivateMultiplierR\x11privateMultiplierB<Z:github.com/johannww/phd-impl/chaincodes/common/internal/pbb\x06proto3"

var (
	file_bids_proto_rawDescOnce sync.Once
	file_bids_proto_rawDescData []byte
)

func file_bids_proto_rawDescGZIP() []byte {
	file_bids_proto_rawDescOnce.Do(func() {
		file_bids_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bids_proto_rawDesc), len(file_bids_proto_rawDesc)))
	})
	return file_bids_proto_rawDescData
}

var file_bids_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bids_proto_goTypes = []any{
	(*PrivatePrice)(nil),      // 0: pb.PrivatePrice
	(*PrivateQuantity)(nil),   // 1: pb.PrivateQuantity
	(*PrivateMultiplier)(nil), // 2: pb.PrivateMultiplier
	(*BuyBid)(nil),            // 3: pb.BuyBid
	(*SellBid)(nil),           // 4: pb.SellBid
	(*MatchedBid)(nil),        // 5: pb.MatchedBid
	(*MintCredit)(nil),        // 6: pb.MintCredit
}
var file_bids_proto_depIdxs = []int32{
	1, // 0: pb.BuyBid.privateQuantity:type_name -> pb.PrivateQuantity
	0, // 1: pb.BuyBid.privatePrice:type_name -> pb.PrivatePrice
	6, // 2: pb.SellBid.credit:type_name -> pb.MintCredit
	0, // 3: pb.SellBid.privatePrice:type_name -> pb.PrivatePrice
	3, // 4: pb.MatchedBid.buyBid:type_name -> pb.BuyBid
	4, // 5: pb.MatchedBid.sellBid:type_name -> pb.SellBid
	0, // 6: pb.MatchedBid.privatePrice:type_name -> pb.PrivatePrice
	2, // 7: pb.MatchedBid.privateMultiplier:type_name -> pb.PrivateMultiplier
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_bids_proto_init() }
func file_bids_proto_init() {
	if File_bids_proto != nil {
		return
	}
	file_credits_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bids_proto_rawDesc), len(file_bids_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bids_proto_goTypes,
		DependencyIndexes: file_bids_proto_depIdxs,
		MessageInfos:      file_bids_proto_msgTypes,
	}.Build()
	File_bids_proto = out.File
	file_bids_proto_goTypes = nil
	file_bids_proto_depIdxs = nil
}
