// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.33.1
// source: companies.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pseudonym to CompanyID mapping
type PseudonymToCompanyID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pseudonym     string                 `protobuf:"bytes,1,opt,name=pseudonym,proto3" json:"pseudonym,omitempty"`
	CompanyID     string                 `protobuf:"bytes,2,opt,name=companyID,proto3" json:"companyID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PseudonymToCompanyID) Reset() {
	*x = PseudonymToCompanyID{}
	mi := &file_companies_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PseudonymToCompanyID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PseudonymToCompanyID) ProtoMessage() {}

func (x *PseudonymToCompanyID) ProtoReflect() protoreflect.Message {
	mi := &file_companies_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PseudonymToCompanyID.ProtoReflect.Descriptor instead.
func (*PseudonymToCompanyID) Descriptor() ([]byte, []int) {
	return file_companies_proto_rawDescGZIP(), []int{0}
}

func (x *PseudonymToCompanyID) GetPseudonym() string {
	if x != nil {
		return x.Pseudonym
	}
	return ""
}

func (x *PseudonymToCompanyID) GetCompanyID() string {
	if x != nil {
		return x.CompanyID
	}
	return ""
}

var File_companies_proto protoreflect.FileDescriptor

const file_companies_proto_rawDesc = "" +
	"\n" +
	"\x0fcompanies.proto\x12\x02pb\"R\n" +
	"\x14PseudonymToCompanyID\x12\x1c\n" +
	"\tpseudonym\x18\x01 \x01(\tR\tpseudonym\x12\x1c\n" +
	"\tcompanyID\x18\x02 \x01(\tR\tcompanyIDB<Z:github.com/johannww/phd-impl/chaincodes/common/internal/pbb\x06proto3"

var (
	file_companies_proto_rawDescOnce sync.Once
	file_companies_proto_rawDescData []byte
)

func file_companies_proto_rawDescGZIP() []byte {
	file_companies_proto_rawDescOnce.Do(func() {
		file_companies_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_companies_proto_rawDesc), len(file_companies_proto_rawDesc)))
	})
	return file_companies_proto_rawDescData
}

var file_companies_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_companies_proto_goTypes = []any{
	(*PseudonymToCompanyID)(nil), // 0: pb.PseudonymToCompanyID
}
var file_companies_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_companies_proto_init() }
func file_companies_proto_init() {
	if File_companies_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_companies_proto_rawDesc), len(file_companies_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_companies_proto_goTypes,
		DependencyIndexes: file_companies_proto_depIdxs,
		MessageInfos:      file_companies_proto_msgTypes,
	}.Build()
	File_companies_proto = out.File
	file_companies_proto_goTypes = nil
	file_companies_proto_depIdxs = nil
}
