// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.33.1
// source: credits.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	ChunkId       []string               `protobuf:"bytes,2,rep,name=chunkId,proto3" json:"chunkId,omitempty"`
	Chunk         *PropertyChunk         `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credit) Reset() {
	*x = Credit{}
	mi := &file_credits_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credit) ProtoMessage() {}

func (x *Credit) ProtoReflect() protoreflect.Message {
	mi := &file_credits_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credit.ProtoReflect.Descriptor instead.
func (*Credit) Descriptor() ([]byte, []int) {
	return file_credits_proto_rawDescGZIP(), []int{0}
}

func (x *Credit) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Credit) GetChunkId() []string {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *Credit) GetChunk() *PropertyChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *Credit) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type MintCredit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credit        *Credit                `protobuf:"bytes,1,opt,name=credit,proto3" json:"credit,omitempty"`
	MintMult      int64                  `protobuf:"varint,2,opt,name=mintMult,proto3" json:"mintMult,omitempty"`
	MintTimestamp string                 `protobuf:"bytes,3,opt,name=mintTimestamp,proto3" json:"mintTimestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintCredit) Reset() {
	*x = MintCredit{}
	mi := &file_credits_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintCredit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintCredit) ProtoMessage() {}

func (x *MintCredit) ProtoReflect() protoreflect.Message {
	mi := &file_credits_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintCredit.ProtoReflect.Descriptor instead.
func (*MintCredit) Descriptor() ([]byte, []int) {
	return file_credits_proto_rawDescGZIP(), []int{1}
}

func (x *MintCredit) GetCredit() *Credit {
	if x != nil {
		return x.Credit
	}
	return nil
}

func (x *MintCredit) GetMintMult() int64 {
	if x != nil {
		return x.MintMult
	}
	return 0
}

func (x *MintCredit) GetMintTimestamp() string {
	if x != nil {
		return x.MintTimestamp
	}
	return ""
}

type BurnCredit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MintCreditID  []string               `protobuf:"bytes,1,rep,name=mintCreditID,proto3" json:"mintCreditID,omitempty"`
	MintCredit    *MintCredit            `protobuf:"bytes,2,opt,name=mintCredit,proto3" json:"mintCredit,omitempty"`
	BurnQuantity  int64                  `protobuf:"varint,3,opt,name=burnQuantity,proto3" json:"burnQuantity,omitempty"`
	BurnMult      int64                  `protobuf:"varint,4,opt,name=burnMult,proto3" json:"burnMult,omitempty"`
	BurnTimestamp string                 `protobuf:"bytes,5,opt,name=burnTimestamp,proto3" json:"burnTimestamp,omitempty"`
	Adjusted      bool                   `protobuf:"varint,6,opt,name=adjusted,proto3" json:"adjusted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BurnCredit) Reset() {
	*x = BurnCredit{}
	mi := &file_credits_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnCredit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnCredit) ProtoMessage() {}

func (x *BurnCredit) ProtoReflect() protoreflect.Message {
	mi := &file_credits_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnCredit.ProtoReflect.Descriptor instead.
func (*BurnCredit) Descriptor() ([]byte, []int) {
	return file_credits_proto_rawDescGZIP(), []int{2}
}

func (x *BurnCredit) GetMintCreditID() []string {
	if x != nil {
		return x.MintCreditID
	}
	return nil
}

func (x *BurnCredit) GetMintCredit() *MintCredit {
	if x != nil {
		return x.MintCredit
	}
	return nil
}

func (x *BurnCredit) GetBurnQuantity() int64 {
	if x != nil {
		return x.BurnQuantity
	}
	return 0
}

func (x *BurnCredit) GetBurnMult() int64 {
	if x != nil {
		return x.BurnMult
	}
	return 0
}

func (x *BurnCredit) GetBurnTimestamp() string {
	if x != nil {
		return x.BurnTimestamp
	}
	return ""
}

func (x *BurnCredit) GetAdjusted() bool {
	if x != nil {
		return x.Adjusted
	}
	return false
}

type CreditWallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditWallet) Reset() {
	*x = CreditWallet{}
	mi := &file_credits_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditWallet) ProtoMessage() {}

func (x *CreditWallet) ProtoReflect() protoreflect.Message {
	mi := &file_credits_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditWallet.ProtoReflect.Descriptor instead.
func (*CreditWallet) Descriptor() ([]byte, []int) {
	return file_credits_proto_rawDescGZIP(), []int{3}
}

func (x *CreditWallet) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CreditWallet) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type LockedCredit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreditID      []string               `protobuf:"bytes,1,rep,name=creditID,proto3" json:"creditID,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LockID        string                 `protobuf:"bytes,3,opt,name=lockID,proto3" json:"lockID,omitempty"`
	DestChainID   string                 `protobuf:"bytes,4,opt,name=destChainID,proto3" json:"destChainID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockedCredit) Reset() {
	*x = LockedCredit{}
	mi := &file_credits_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockedCredit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockedCredit) ProtoMessage() {}

func (x *LockedCredit) ProtoReflect() protoreflect.Message {
	mi := &file_credits_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockedCredit.ProtoReflect.Descriptor instead.
func (*LockedCredit) Descriptor() ([]byte, []int) {
	return file_credits_proto_rawDescGZIP(), []int{4}
}

func (x *LockedCredit) GetCreditID() []string {
	if x != nil {
		return x.CreditID
	}
	return nil
}

func (x *LockedCredit) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *LockedCredit) GetLockID() string {
	if x != nil {
		return x.LockID
	}
	return ""
}

func (x *LockedCredit) GetDestChainID() string {
	if x != nil {
		return x.DestChainID
	}
	return ""
}

var File_credits_proto protoreflect.FileDescriptor

const file_credits_proto_rawDesc = "" +
	"\n" +
	"\rcredits.proto\x12\x02pb\x1a\x10properties.proto\"}\n" +
	"\x06Credit\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x18\n" +
	"\achunkId\x18\x02 \x03(\tR\achunkId\x12'\n" +
	"\x05chunk\x18\x03 \x01(\v2\x11.pb.PropertyChunkR\x05chunk\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"r\n" +
	"\n" +
	"MintCredit\x12\"\n" +
	"\x06credit\x18\x01 \x01(\v2\n" +
	".pb.CreditR\x06credit\x12\x1a\n" +
	"\bmintMult\x18\x02 \x01(\x03R\bmintMult\x12$\n" +
	"\rmintTimestamp\x18\x03 \x01(\tR\rmintTimestamp\"\xe2\x01\n" +
	"\n" +
	"BurnCredit\x12\"\n" +
	"\fmintCreditID\x18\x01 \x03(\tR\fmintCreditID\x12.\n" +
	"\n" +
	"mintCredit\x18\x02 \x01(\v2\x0e.pb.MintCreditR\n" +
	"mintCredit\x12\"\n" +
	"\fburnQuantity\x18\x03 \x01(\x03R\fburnQuantity\x12\x1a\n" +
	"\bburnMult\x18\x04 \x01(\x03R\bburnMult\x12$\n" +
	"\rburnTimestamp\x18\x05 \x01(\tR\rburnTimestamp\x12\x1a\n" +
	"\badjusted\x18\x06 \x01(\bR\badjusted\"@\n" +
	"\fCreditWallet\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"\x80\x01\n" +
	"\fLockedCredit\x12\x1a\n" +
	"\bcreditID\x18\x01 \x03(\tR\bcreditID\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12\x16\n" +
	"\x06lockID\x18\x03 \x01(\tR\x06lockID\x12 \n" +
	"\vdestChainID\x18\x04 \x01(\tR\vdestChainIDB<Z:github.com/johannww/phd-impl/chaincodes/common/internal/pbb\x06proto3"

var (
	file_credits_proto_rawDescOnce sync.Once
	file_credits_proto_rawDescData []byte
)

func file_credits_proto_rawDescGZIP() []byte {
	file_credits_proto_rawDescOnce.Do(func() {
		file_credits_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credits_proto_rawDesc), len(file_credits_proto_rawDesc)))
	})
	return file_credits_proto_rawDescData
}

var file_credits_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_credits_proto_goTypes = []any{
	(*Credit)(nil),        // 0: pb.Credit
	(*MintCredit)(nil),    // 1: pb.MintCredit
	(*BurnCredit)(nil),    // 2: pb.BurnCredit
	(*CreditWallet)(nil),  // 3: pb.CreditWallet
	(*LockedCredit)(nil),  // 4: pb.LockedCredit
	(*PropertyChunk)(nil), // 5: pb.PropertyChunk
}
var file_credits_proto_depIdxs = []int32{
	5, // 0: pb.Credit.chunk:type_name -> pb.PropertyChunk
	0, // 1: pb.MintCredit.credit:type_name -> pb.Credit
	1, // 2: pb.BurnCredit.mintCredit:type_name -> pb.MintCredit
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_credits_proto_init() }
func file_credits_proto_init() {
	if File_credits_proto != nil {
		return
	}
	file_properties_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credits_proto_rawDesc), len(file_credits_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_credits_proto_goTypes,
		DependencyIndexes: file_credits_proto_depIdxs,
		MessageInfos:      file_credits_proto_msgTypes,
	}.Build()
	File_credits_proto = out.File
	file_credits_proto_goTypes = nil
	file_credits_proto_depIdxs = nil
}
