// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v7.34.1
// source: htlc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HTLC represents a hash-time-locked contract record used for cross-chain
// credit transfers. Field names follow the project's JSON naming conventions
// and use lowerCamelCase for proto field names.
type HTLC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owner of the credit(s) (first element of CreditID is owner id in the app)
	CreditID []string `protobuf:"bytes,1,rep,name=creditID,proto3" json:"creditID,omitempty"`
	// Hash of the preimage (sha256 hex or base64)
	SecretHash string `protobuf:"bytes,2,opt,name=secretHash,proto3" json:"secretHash,omitempty"`
	// Preimage (only present when claimed)
	Secret string `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	// Lock identifier
	LockID string `protobuf:"bytes,4,opt,name=lockID,proto3" json:"lockID,omitempty"`
	// Receiver identity on the destination chain
	ReceiverId string `protobuf:"bytes,5,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	// Payment receiver wallet (on public chain)
	PaymentReceiverWallet string `protobuf:"bytes,6,opt,name=paymentReceiverWallet,proto3" json:"paymentReceiverWallet,omitempty"`
	// Amount (use int64 to be safe for proto int handling)
	Amount int64 `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	// Whether the HTLC has been claimed
	Claimed bool `protobuf:"varint,8,opt,name=claimed,proto3" json:"claimed,omitempty"`
	// RFC3339 timestamp until which the HTLC is valid
	ValidUntil    string `protobuf:"bytes,9,opt,name=validUntil,proto3" json:"validUntil,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTLC) Reset() {
	*x = HTLC{}
	mi := &file_htlc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTLC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTLC) ProtoMessage() {}

func (x *HTLC) ProtoReflect() protoreflect.Message {
	mi := &file_htlc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTLC.ProtoReflect.Descriptor instead.
func (*HTLC) Descriptor() ([]byte, []int) {
	return file_htlc_proto_rawDescGZIP(), []int{0}
}

func (x *HTLC) GetCreditID() []string {
	if x != nil {
		return x.CreditID
	}
	return nil
}

func (x *HTLC) GetSecretHash() string {
	if x != nil {
		return x.SecretHash
	}
	return ""
}

func (x *HTLC) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *HTLC) GetLockID() string {
	if x != nil {
		return x.LockID
	}
	return ""
}

func (x *HTLC) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *HTLC) GetPaymentReceiverWallet() string {
	if x != nil {
		return x.PaymentReceiverWallet
	}
	return ""
}

func (x *HTLC) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *HTLC) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *HTLC) GetValidUntil() string {
	if x != nil {
		return x.ValidUntil
	}
	return ""
}

var File_htlc_proto protoreflect.FileDescriptor

const file_htlc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"htlc.proto\x12\x02pb\"\x9a\x02\n" +
	"\x04HTLC\x12\x1a\n" +
	"\bcreditID\x18\x01 \x03(\tR\bcreditID\x12\x1e\n" +
	"\n" +
	"secretHash\x18\x02 \x01(\tR\n" +
	"secretHash\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x16\n" +
	"\x06lockID\x18\x04 \x01(\tR\x06lockID\x12\x1e\n" +
	"\n" +
	"receiverId\x18\x05 \x01(\tR\n" +
	"receiverId\x124\n" +
	"\x15paymentReceiverWallet\x18\x06 \x01(\tR\x15paymentReceiverWallet\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12\x18\n" +
	"\aclaimed\x18\b \x01(\bR\aclaimed\x12\x1e\n" +
	"\n" +
	"validUntil\x18\t \x01(\tR\n" +
	"validUntilB3Z1github.com/johannww/phd-impl/chaincodes/common/pbb\x06proto3"

var (
	file_htlc_proto_rawDescOnce sync.Once
	file_htlc_proto_rawDescData []byte
)

func file_htlc_proto_rawDescGZIP() []byte {
	file_htlc_proto_rawDescOnce.Do(func() {
		file_htlc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_htlc_proto_rawDesc), len(file_htlc_proto_rawDesc)))
	})
	return file_htlc_proto_rawDescData
}

var file_htlc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_htlc_proto_goTypes = []any{
	(*HTLC)(nil), // 0: pb.HTLC
}
var file_htlc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_htlc_proto_init() }
func file_htlc_proto_init() {
	if File_htlc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_htlc_proto_rawDesc), len(file_htlc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_htlc_proto_goTypes,
		DependencyIndexes: file_htlc_proto_depIdxs,
		MessageInfos:      file_htlc_proto_msgTypes,
	}.Build()
	File_htlc_proto = out.File
	file_htlc_proto_goTypes = nil
	file_htlc_proto_depIdxs = nil
}
