// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.33.1
// source: properties.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForestType int32

const (
	ForestType_AMAZON_RAINFOREST ForestType = 0
	ForestType_ATLANTIC_FOREST   ForestType = 1
	ForestType_CAATINGA          ForestType = 2
	ForestType_CERRADO           ForestType = 3
	ForestType_PANTANAL          ForestType = 4
	ForestType_PAMPA             ForestType = 5
	ForestType_MANGROVES         ForestType = 6
	ForestType_ARAUCARIA_FOREST  ForestType = 7
	ForestType_RESTINGA          ForestType = 8
)

// Enum value maps for ForestType.
var (
	ForestType_name = map[int32]string{
		0: "AMAZON_RAINFOREST",
		1: "ATLANTIC_FOREST",
		2: "CAATINGA",
		3: "CERRADO",
		4: "PANTANAL",
		5: "PAMPA",
		6: "MANGROVES",
		7: "ARAUCARIA_FOREST",
		8: "RESTINGA",
	}
	ForestType_value = map[string]int32{
		"AMAZON_RAINFOREST": 0,
		"ATLANTIC_FOREST":   1,
		"CAATINGA":          2,
		"CERRADO":           3,
		"PANTANAL":          4,
		"PAMPA":             5,
		"MANGROVES":         6,
		"ARAUCARIA_FOREST":  7,
		"RESTINGA":          8,
	}
)

func (x ForestType) Enum() *ForestType {
	p := new(ForestType)
	*p = x
	return p
}

func (x ForestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForestType) Descriptor() protoreflect.EnumDescriptor {
	return file_properties_proto_enumTypes[0].Descriptor()
}

func (ForestType) Type() protoreflect.EnumType {
	return &file_properties_proto_enumTypes[0]
}

func (x ForestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForestType.Descriptor instead.
func (ForestType) EnumDescriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{0}
}

type CropType int32

const (
	CropType_SOYBEAN   CropType = 0
	CropType_CORN      CropType = 1
	CropType_COFFEE    CropType = 2
	CropType_SUGARCANE CropType = 3
	CropType_COTTON    CropType = 4
	CropType_RICE      CropType = 5
	CropType_WHEAT     CropType = 6
	CropType_BEANS     CropType = 7
	CropType_ORANGE    CropType = 8
	CropType_BANANA    CropType = 9
)

// Enum value maps for CropType.
var (
	CropType_name = map[int32]string{
		0: "SOYBEAN",
		1: "CORN",
		2: "COFFEE",
		3: "SUGARCANE",
		4: "COTTON",
		5: "RICE",
		6: "WHEAT",
		7: "BEANS",
		8: "ORANGE",
		9: "BANANA",
	}
	CropType_value = map[string]int32{
		"SOYBEAN":   0,
		"CORN":      1,
		"COFFEE":    2,
		"SUGARCANE": 3,
		"COTTON":    4,
		"RICE":      5,
		"WHEAT":     6,
		"BEANS":     7,
		"ORANGE":    8,
		"BANANA":    9,
	}
)

func (x CropType) Enum() *CropType {
	p := new(CropType)
	*p = x
	return p
}

func (x CropType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CropType) Descriptor() protoreflect.EnumDescriptor {
	return file_properties_proto_enumTypes[1].Descriptor()
}

func (CropType) Type() protoreflect.EnumType {
	return &file_properties_proto_enumTypes[1]
}

func (x CropType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CropType.Descriptor instead.
func (CropType) EnumDescriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{1}
}

type ValidationMethod int32

const (
	ValidationMethod_SATELLITE        ValidationMethod = 0
	ValidationMethod_GROUND_TRUTH     ValidationMethod = 1
	ValidationMethod_SELF_DECLARATION ValidationMethod = 2
)

// Enum value maps for ValidationMethod.
var (
	ValidationMethod_name = map[int32]string{
		0: "SATELLITE",
		1: "GROUND_TRUTH",
		2: "SELF_DECLARATION",
	}
	ValidationMethod_value = map[string]int32{
		"SATELLITE":        0,
		"GROUND_TRUTH":     1,
		"SELF_DECLARATION": 2,
	}
)

func (x ValidationMethod) Enum() *ValidationMethod {
	p := new(ValidationMethod)
	*p = x
	return p
}

func (x ValidationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_properties_proto_enumTypes[2].Descriptor()
}

func (ValidationMethod) Type() protoreflect.EnumType {
	return &file_properties_proto_enumTypes[2]
}

func (x ValidationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationMethod.Descriptor instead.
func (ValidationMethod) EnumDescriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{2}
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_properties_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_properties_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type VegetationProps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForestType    ForestType             `protobuf:"varint,1,opt,name=forestType,proto3,enum=pb.ForestType" json:"forestType,omitempty"`
	ForestDensity float64                `protobuf:"fixed64,2,opt,name=forestDensity,proto3" json:"forestDensity,omitempty"`
	CropType      CropType               `protobuf:"varint,3,opt,name=cropType,proto3,enum=pb.CropType" json:"cropType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VegetationProps) Reset() {
	*x = VegetationProps{}
	mi := &file_properties_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VegetationProps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VegetationProps) ProtoMessage() {}

func (x *VegetationProps) ProtoReflect() protoreflect.Message {
	mi := &file_properties_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VegetationProps.ProtoReflect.Descriptor instead.
func (*VegetationProps) Descriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{1}
}

func (x *VegetationProps) GetForestType() ForestType {
	if x != nil {
		return x.ForestType
	}
	return ForestType_AMAZON_RAINFOREST
}

func (x *VegetationProps) GetForestDensity() float64 {
	if x != nil {
		return x.ForestDensity
	}
	return 0
}

func (x *VegetationProps) GetCropType() CropType {
	if x != nil {
		return x.CropType
	}
	return CropType_SOYBEAN
}

type ValidationProps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []ValidationMethod     `protobuf:"varint,1,rep,packed,name=methods,proto3,enum=pb.ValidationMethod" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationProps) Reset() {
	*x = ValidationProps{}
	mi := &file_properties_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationProps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationProps) ProtoMessage() {}

func (x *ValidationProps) ProtoReflect() protoreflect.Message {
	mi := &file_properties_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationProps.ProtoReflect.Descriptor instead.
func (*ValidationProps) Descriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationProps) GetMethods() []ValidationMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

type PropertyChunk struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PropertyId       uint64                 `protobuf:"varint,1,opt,name=propertyId,proto3" json:"propertyId,omitempty"`
	Coordinates      []*Coordinate          `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	VegetationsProps *VegetationProps       `protobuf:"bytes,3,opt,name=vegetationsProps,proto3" json:"vegetationsProps,omitempty"`
	ValidationProps  *ValidationProps       `protobuf:"bytes,4,opt,name=validationProps,proto3" json:"validationProps,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PropertyChunk) Reset() {
	*x = PropertyChunk{}
	mi := &file_properties_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyChunk) ProtoMessage() {}

func (x *PropertyChunk) ProtoReflect() protoreflect.Message {
	mi := &file_properties_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyChunk.ProtoReflect.Descriptor instead.
func (*PropertyChunk) Descriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{3}
}

func (x *PropertyChunk) GetPropertyId() uint64 {
	if x != nil {
		return x.PropertyId
	}
	return 0
}

func (x *PropertyChunk) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *PropertyChunk) GetVegetationsProps() *VegetationProps {
	if x != nil {
		return x.VegetationsProps
	}
	return nil
}

func (x *PropertyChunk) GetValidationProps() *ValidationProps {
	if x != nil {
		return x.ValidationProps
	}
	return nil
}

type Property struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OwnerId          string                 `protobuf:"bytes,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Id               uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	RegistryId       string                 `protobuf:"bytes,3,opt,name=registryId,proto3" json:"registryId,omitempty"`
	RegistryProvider string                 `protobuf:"bytes,4,opt,name=registryProvider,proto3" json:"registryProvider,omitempty"`
	Chunks           []*PropertyChunk       `protobuf:"bytes,5,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_properties_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_properties_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{4}
}

func (x *Property) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Property) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Property) GetRegistryId() string {
	if x != nil {
		return x.RegistryId
	}
	return ""
}

func (x *Property) GetRegistryProvider() string {
	if x != nil {
		return x.RegistryProvider
	}
	return ""
}

func (x *Property) GetChunks() []*PropertyChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type RegistrySummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RegistryPropId  string                 `protobuf:"bytes,1,opt,name=registryPropId,proto3" json:"registryPropId,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TotalArea       float64                `protobuf:"fixed64,3,opt,name=totalArea,proto3" json:"totalArea,omitempty"`
	LegalForestArea float64                `protobuf:"fixed64,4,opt,name=legalForestArea,proto3" json:"legalForestArea,omitempty"`
	VerifiedForest  float64                `protobuf:"fixed64,5,opt,name=verifiedForest,proto3" json:"verifiedForest,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegistrySummary) Reset() {
	*x = RegistrySummary{}
	mi := &file_properties_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrySummary) ProtoMessage() {}

func (x *RegistrySummary) ProtoReflect() protoreflect.Message {
	mi := &file_properties_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrySummary.ProtoReflect.Descriptor instead.
func (*RegistrySummary) Descriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{5}
}

func (x *RegistrySummary) GetRegistryPropId() string {
	if x != nil {
		return x.RegistryPropId
	}
	return ""
}

func (x *RegistrySummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegistrySummary) GetTotalArea() float64 {
	if x != nil {
		return x.TotalArea
	}
	return 0
}

func (x *RegistrySummary) GetLegalForestArea() float64 {
	if x != nil {
		return x.LegalForestArea
	}
	return 0
}

func (x *RegistrySummary) GetVerifiedForest() float64 {
	if x != nil {
		return x.VerifiedForest
	}
	return 0
}

type RegistryProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=baseUrl,proto3" json:"baseUrl,omitempty"`
	RootCa        []byte                 `protobuf:"bytes,3,opt,name=rootCa,proto3" json:"rootCa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryProvider) Reset() {
	*x = RegistryProvider{}
	mi := &file_properties_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryProvider) ProtoMessage() {}

func (x *RegistryProvider) ProtoReflect() protoreflect.Message {
	mi := &file_properties_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryProvider.ProtoReflect.Descriptor instead.
func (*RegistryProvider) Descriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{6}
}

func (x *RegistryProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryProvider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *RegistryProvider) GetRootCa() []byte {
	if x != nil {
		return x.RootCa
	}
	return nil
}

type Temperature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinate    *Coordinate            `protobuf:"bytes,1,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Datetime      string                 `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Temperature) Reset() {
	*x = Temperature{}
	mi := &file_properties_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Temperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temperature) ProtoMessage() {}

func (x *Temperature) ProtoReflect() protoreflect.Message {
	mi := &file_properties_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temperature.ProtoReflect.Descriptor instead.
func (*Temperature) Descriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{7}
}

func (x *Temperature) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *Temperature) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *Temperature) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type Wind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinate    *Coordinate            `protobuf:"bytes,1,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Datetime      string                 `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Speed         float64                `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Direction     float64                `protobuf:"fixed64,4,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wind) Reset() {
	*x = Wind{}
	mi := &file_properties_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wind) ProtoMessage() {}

func (x *Wind) ProtoReflect() protoreflect.Message {
	mi := &file_properties_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wind.ProtoReflect.Descriptor instead.
func (*Wind) Descriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{8}
}

func (x *Wind) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *Wind) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *Wind) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Wind) GetDirection() float64 {
	if x != nil {
		return x.Direction
	}
	return 0
}

type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	DataProps     *ValidationProps       `protobuf:"bytes,3,opt,name=dataProps,proto3" json:"dataProps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_properties_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_properties_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_properties_proto_rawDescGZIP(), []int{9}
}

func (x *Company) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Company) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *Company) GetDataProps() *ValidationProps {
	if x != nil {
		return x.DataProps
	}
	return nil
}

var File_properties_proto protoreflect.FileDescriptor

const file_properties_proto_rawDesc = "" +
	"\n" +
	"\x10properties.proto\x12\x02pb\"F\n" +
	"\n" +
	"Coordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\x91\x01\n" +
	"\x0fVegetationProps\x12.\n" +
	"\n" +
	"forestType\x18\x01 \x01(\x0e2\x0e.pb.ForestTypeR\n" +
	"forestType\x12$\n" +
	"\rforestDensity\x18\x02 \x01(\x01R\rforestDensity\x12(\n" +
	"\bcropType\x18\x03 \x01(\x0e2\f.pb.CropTypeR\bcropType\"A\n" +
	"\x0fValidationProps\x12.\n" +
	"\amethods\x18\x01 \x03(\x0e2\x14.pb.ValidationMethodR\amethods\"\xe1\x01\n" +
	"\rPropertyChunk\x12\x1e\n" +
	"\n" +
	"propertyId\x18\x01 \x01(\x04R\n" +
	"propertyId\x120\n" +
	"\vcoordinates\x18\x02 \x03(\v2\x0e.pb.CoordinateR\vcoordinates\x12?\n" +
	"\x10vegetationsProps\x18\x03 \x01(\v2\x13.pb.VegetationPropsR\x10vegetationsProps\x12=\n" +
	"\x0fvalidationProps\x18\x04 \x01(\v2\x13.pb.ValidationPropsR\x0fvalidationProps\"\xab\x01\n" +
	"\bProperty\x12\x18\n" +
	"\aownerId\x18\x01 \x01(\tR\aownerId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x1e\n" +
	"\n" +
	"registryId\x18\x03 \x01(\tR\n" +
	"registryId\x12*\n" +
	"\x10registryProvider\x18\x04 \x01(\tR\x10registryProvider\x12)\n" +
	"\x06chunks\x18\x05 \x03(\v2\x11.pb.PropertyChunkR\x06chunks\"\xc1\x01\n" +
	"\x0fRegistrySummary\x12&\n" +
	"\x0eregistryPropId\x18\x01 \x01(\tR\x0eregistryPropId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\ttotalArea\x18\x03 \x01(\x01R\ttotalArea\x12(\n" +
	"\x0flegalForestArea\x18\x04 \x01(\x01R\x0flegalForestArea\x12&\n" +
	"\x0everifiedForest\x18\x05 \x01(\x01R\x0everifiedForest\"X\n" +
	"\x10RegistryProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\abaseUrl\x18\x02 \x01(\tR\abaseUrl\x12\x16\n" +
	"\x06rootCa\x18\x03 \x01(\fR\x06rootCa\"{\n" +
	"\vTemperature\x12.\n" +
	"\n" +
	"coordinate\x18\x01 \x01(\v2\x0e.pb.CoordinateR\n" +
	"coordinate\x12\x1a\n" +
	"\bdatetime\x18\x02 \x01(\tR\bdatetime\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\"\x86\x01\n" +
	"\x04Wind\x12.\n" +
	"\n" +
	"coordinate\x18\x01 \x01(\v2\x0e.pb.CoordinateR\n" +
	"coordinate\x12\x1a\n" +
	"\bdatetime\x18\x02 \x01(\tR\bdatetime\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x01R\x05speed\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\x01R\tdirection\"|\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x0e.pb.CoordinateR\n" +
	"coordinate\x121\n" +
	"\tdataProps\x18\x03 \x01(\v2\x13.pb.ValidationPropsR\tdataProps*\x9f\x01\n" +
	"\n" +
	"ForestType\x12\x15\n" +
	"\x11AMAZON_RAINFOREST\x10\x00\x12\x13\n" +
	"\x0fATLANTIC_FOREST\x10\x01\x12\f\n" +
	"\bCAATINGA\x10\x02\x12\v\n" +
	"\aCERRADO\x10\x03\x12\f\n" +
	"\bPANTANAL\x10\x04\x12\t\n" +
	"\x05PAMPA\x10\x05\x12\r\n" +
	"\tMANGROVES\x10\x06\x12\x14\n" +
	"\x10ARAUCARIA_FOREST\x10\a\x12\f\n" +
	"\bRESTINGA\x10\b*\x80\x01\n" +
	"\bCropType\x12\v\n" +
	"\aSOYBEAN\x10\x00\x12\b\n" +
	"\x04CORN\x10\x01\x12\n" +
	"\n" +
	"\x06COFFEE\x10\x02\x12\r\n" +
	"\tSUGARCANE\x10\x03\x12\n" +
	"\n" +
	"\x06COTTON\x10\x04\x12\b\n" +
	"\x04RICE\x10\x05\x12\t\n" +
	"\x05WHEAT\x10\x06\x12\t\n" +
	"\x05BEANS\x10\a\x12\n" +
	"\n" +
	"\x06ORANGE\x10\b\x12\n" +
	"\n" +
	"\x06BANANA\x10\t*I\n" +
	"\x10ValidationMethod\x12\r\n" +
	"\tSATELLITE\x10\x00\x12\x10\n" +
	"\fGROUND_TRUTH\x10\x01\x12\x14\n" +
	"\x10SELF_DECLARATION\x10\x02B<Z:github.com/johannww/phd-impl/chaincodes/common/internal/pbb\x06proto3"

var (
	file_properties_proto_rawDescOnce sync.Once
	file_properties_proto_rawDescData []byte
)

func file_properties_proto_rawDescGZIP() []byte {
	file_properties_proto_rawDescOnce.Do(func() {
		file_properties_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_properties_proto_rawDesc), len(file_properties_proto_rawDesc)))
	})
	return file_properties_proto_rawDescData
}

var file_properties_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_properties_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_properties_proto_goTypes = []any{
	(ForestType)(0),          // 0: pb.ForestType
	(CropType)(0),            // 1: pb.CropType
	(ValidationMethod)(0),    // 2: pb.ValidationMethod
	(*Coordinate)(nil),       // 3: pb.Coordinate
	(*VegetationProps)(nil),  // 4: pb.VegetationProps
	(*ValidationProps)(nil),  // 5: pb.ValidationProps
	(*PropertyChunk)(nil),    // 6: pb.PropertyChunk
	(*Property)(nil),         // 7: pb.Property
	(*RegistrySummary)(nil),  // 8: pb.RegistrySummary
	(*RegistryProvider)(nil), // 9: pb.RegistryProvider
	(*Temperature)(nil),      // 10: pb.Temperature
	(*Wind)(nil),             // 11: pb.Wind
	(*Company)(nil),          // 12: pb.Company
}
var file_properties_proto_depIdxs = []int32{
	0,  // 0: pb.VegetationProps.forestType:type_name -> pb.ForestType
	1,  // 1: pb.VegetationProps.cropType:type_name -> pb.CropType
	2,  // 2: pb.ValidationProps.methods:type_name -> pb.ValidationMethod
	3,  // 3: pb.PropertyChunk.coordinates:type_name -> pb.Coordinate
	4,  // 4: pb.PropertyChunk.vegetationsProps:type_name -> pb.VegetationProps
	5,  // 5: pb.PropertyChunk.validationProps:type_name -> pb.ValidationProps
	6,  // 6: pb.Property.chunks:type_name -> pb.PropertyChunk
	3,  // 7: pb.Temperature.coordinate:type_name -> pb.Coordinate
	3,  // 8: pb.Wind.coordinate:type_name -> pb.Coordinate
	3,  // 9: pb.Company.coordinate:type_name -> pb.Coordinate
	5,  // 10: pb.Company.dataProps:type_name -> pb.ValidationProps
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_properties_proto_init() }
func file_properties_proto_init() {
	if File_properties_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_properties_proto_rawDesc), len(file_properties_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_properties_proto_goTypes,
		DependencyIndexes: file_properties_proto_depIdxs,
		EnumInfos:         file_properties_proto_enumTypes,
		MessageInfos:      file_properties_proto_msgTypes,
	}.Build()
	File_properties_proto = out.File
	file_properties_proto_goTypes = nil
	file_properties_proto_depIdxs = nil
}
